import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import Providers from "@/components/Providers";
import "./globals.css";
import StudentNavbar from "@/components/common/student-navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Create a Supabase server client for App Router
  const cookieStore = (await cookies()) as any;
  const supabase = createServerComponentClient({ cookies: () => cookieStore });

  // Get the current session (if any)
  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers session={session}>
          {/* Global student navbar */}
          {/* TODO: Replace hard-coded sessionCount with real data when available */}
          <StudentNavbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
